
import { useState, useEffect } from 'react';
import Layout from '@/components/Layout/Layout';
import PropertyList from '@/components/Property/PropertyList';
import { Property } from '@/types/property';
import { Button } from '@/components/ui/button';
import { Webhook } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { Skeleton } from '@/components/ui/skeleton';

const Properties = () => {
  const [allProperties, setAllProperties] = useState<Property[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [testingWebhook, setTestingWebhook] = useState(false);
  const { toast } = useToast();

  const fetchProperties = async () => {
    try {
      setLoading(true);
      
      // Fetch from the Supabase webhook endpoint
      const response = await fetch('https://xfmguaamogzirnnqktwz.supabase.co/functions/v1/receive-webhook');
      
      if (!response.ok) {
        throw new Error(`Failed to fetch properties: ${response.status} ${response.statusText}`);
      }
      
      const data = await response.json();
      
      if (Array.isArray(data)) {
        // Transform the webhook data to match our Property type if needed
        const properties = data.map((item: any) => ({
          id: item.id || String(Math.random()),
          address: {
            street: item.address || '',
            city: item.city || 'Abilene',
            state: item.state || 'TX',
            zipCode: item.zipCode || '',
            neighborhood: item.neighborhood,
          },
          price: item.price ? Number(item.price) : 0,
          beds: item.beds ? Number(item.beds) : 0,
          baths: item.baths ? Number(item.baths) : 0,
          sqft: item.sqft ? Number(item.sqft) : 0,
          lotSize: item.lotSize,
          yearBuilt: item.yearBuilt,
          propertyType: item.propertyType || 'Other',
          description: item.description || '',
          features: item.features || [],
          hasPool: item.hasPool || false,
          hasGarage: item.hasGarage || false,
          garageSpaces: item.garageSpaces,
          images: item.images || ['/placeholder.svg'],
          status: item.status || 'For Sale',
          listedDate: item.listedDate || new Date().toISOString(),
          agent: item.agent || {
            id: '1',
            name: 'Abilene Commercial',
            phone: '123-456-7890',
            email: 'contact@abilenecommercial.com',
          },
          isFeatured: item.isFeatured || false,
        }));
        
        setAllProperties(properties);
        setError(null);
      } else {
        throw new Error('Invalid data format received from webhook');
      }
    } catch (err: any) {
      console.error('Error fetching properties:', err);
      setError(err.message);
      
      // Notify the user about the error
      toast({
        title: 'Error fetching properties',
        description: 'Could not load properties from the webhook.',
        variant: 'destructive',
      });
    } finally {
      setLoading(false);
    }
  };

  const testWebhook = async () => {
    try {
      setTestingWebhook(true);
      
      // Test sample data to post to the webhook
      const testData = {
        id: "test-" + Date.now(),
        address: "123 Test Street",
        city: "Abilene",
        state: "TX",
        zipCode: "79601",
        price: 299000,
        beds: 3,
        baths: 2,
        sqft: 2000,
        propertyType: "Single Family",
        description: "This is a test property generated by the webhook test button.",
        images: ["/placeholder.svg"],
        status: "For Sale",
        listedDate: new Date().toISOString(),
      };
      
      // Send test data to the webhook
      const response = await fetch('https://xfmguaamogzirnnqktwz.supabase.co/functions/v1/receive-webhook', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(testData),
      });
      
      if (!response.ok) {
        throw new Error(`Test webhook failed: ${response.status} ${response.statusText}`);
      }
      
      toast({
        title: 'Test webhook successful',
        description: 'A test property has been sent to the webhook. Refreshing properties list...',
      });
      
      // Fetch properties after successful test
      await fetchProperties();
      
    } catch (err: any) {
      console.error('Error testing webhook:', err);
      
      toast({
        title: 'Error testing webhook',
        description: err.message,
        variant: 'destructive',
      });
    } finally {
      setTestingWebhook(false);
    }
  };

  useEffect(() => {
    fetchProperties();
    
    // Set up a polling interval to fetch new data periodically
    const intervalId = setInterval(fetchProperties, 30000); // Poll every 30 seconds
    
    return () => {
      clearInterval(intervalId); // Clean up on component unmount
    };
  }, []);

  return (
    <Layout>
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-gray-900">Commercial Properties</h1>
          <p className="text-gray-600 mt-2">Find your perfect commercial space in Abilene and surrounding areas</p>
        </div>

        {loading ? (
          <div className="animate-pulse">
            <div className="h-16 bg-gray-200 rounded mb-4"></div>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {[1, 2, 3, 4, 5, 6].map((i) => (
                <div key={i} className="h-80 bg-gray-200 rounded"></div>
              ))}
            </div>
          </div>
        ) : error ? (
          <div className="text-center py-10">
            <h3 className="text-lg font-medium text-gray-900">Could not load properties</h3>
            <p className="mt-1 text-gray-500">Please try again later.</p>
            <Button 
              onClick={fetchProperties} 
              variant="outline" 
              className="mt-4"
            >
              Retry
            </Button>
          </div>
        ) : allProperties.length > 0 ? (
          <PropertyList initialProperties={allProperties} />
        ) : (
          <div className="text-center py-10">
            <h3 className="text-lg font-medium text-gray-900">No properties found</h3>
            <p className="mt-1 text-gray-500">You can test the webhook by clicking the button below.</p>
            <Button 
              onClick={testWebhook} 
              disabled={testingWebhook}
              variant="estate" 
              className="mt-4 flex items-center gap-2"
            >
              <Webhook size={16} />
              {testingWebhook ? "Sending test data..." : "Test Webhook"}
            </Button>
          </div>
        )}
      </div>
    </Layout>
  );
};

export default Properties;
